version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - '.env'

     # FOR DEVELOPMENT
    ports:
      - '3306:3306'

     # FOR DEPLOY
#    expose:
#      - 3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  web:
    build: .
    restart: on-failure
    ports:
      - '8003:8000'
    env_file:
      - .env

  daemon:
    build: script_daemon/.
    restart: always
    env_file:
      - .env