"""script nullable

Revision ID: 03cfa63df820
Revises: 678f984039ab
Create Date: 2023-06-07 00:55:39.583050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cfa63df820'
down_revision = '678f984039ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
