"""add latency to script_actions

Revision ID: 36350102df59
Revises: e5bcd083edb3
Create Date: 2023-06-10 00:00:29.837111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36350102df59'
down_revision = 'e5bcd083edb3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_actions', sa.Column('latency', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_actions', 'latency')
    # ### end Alembic commands ###
