"""nullable time field of script model

Revision ID: 3959b5315f4e
Revises: a18e8ebfb195
Create Date: 2023-06-21 23:57:16.974498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3959b5315f4e'
down_revision = 'a18e8ebfb195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
