"""script models

Revision ID: 678f984039ab
Revises: f20ab4e76523
Create Date: 2023-06-06 23:57:59.908586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678f984039ab'
down_revision = 'f20ab4e76523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('script_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions_association_table',
    sa.Column('script_action_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['script_action_id'], ['script_actions.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('script_action_id', 'script_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions_association_table')
    op.drop_table('script_actions')
    op.drop_table('actions')
    op.drop_table('scripts')
    op.drop_table('devices')
    # ### end Alembic commands ###
