"""device_id field add

Revision ID: 8dc9bc6ebe63
Revises: 03cfa63df820
Create Date: 2023-06-08 16:09:19.891987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8dc9bc6ebe63'
down_revision = '03cfa63df820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('device_type', sa.Integer(), nullable=True))
    op.drop_constraint('actions_ibfk_1', 'actions', type_='foreignkey')
    op.create_foreign_key(None, 'actions', 'devices', ['device_type'], ['id'])
    op.drop_column('actions', 'device_id')
    op.add_column('script_actions', sa.Column('device_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_actions', 'device_id')
    op.add_column('actions', sa.Column('device_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.create_foreign_key('actions_ibfk_1', 'actions', 'devices', ['device_id'], ['id'])
    op.drop_column('actions', 'device_type')
    # ### end Alembic commands ###
