"""fix foreign key

Revision ID: 9c8b3a301d2c
Revises: e78e684796a9
Create Date: 2023-06-01 17:45:26.512051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c8b3a301d2c'
down_revision = 'e78e684796a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('buttons_ibfk_1', 'buttons', type_='foreignkey')
    op.create_foreign_key(None, 'buttons', 'user', ['owner_id'], ['id'])
    op.drop_column('buttons', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('owner', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buttons', type_='foreignkey')
    op.create_foreign_key('buttons_ibfk_1', 'buttons', 'user', ['owner'], ['id'])
    op.drop_column('buttons', 'owner_id')
    # ### end Alembic commands ###
