"""nullable duration

Revision ID: e59dd02c05aa
Revises: 8dc9bc6ebe63
Create Date: 2023-06-09 21:51:11.672777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e59dd02c05aa'
down_revision = '8dc9bc6ebe63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
