"""added foreign key

Revision ID: e78e684796a9
Revises: 506b3c550b16
Create Date: 2023-06-01 17:24:20.522068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78e684796a9'
down_revision = '506b3c550b16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
