"""token add

Revision ID: f20ab4e76523
Revises: 9c8b3a301d2c
Create Date: 2023-06-03 11:00:25.959931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20ab4e76523'
down_revision = '9c8b3a301d2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buttons', sa.Column('token', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buttons', 'token')
    # ### end Alembic commands ###
